### ISSUE TITLE
Crash on LiveSigns

### ISSUE THREAD

**Issue by inxomnyaa** [alejandroliu/pocketmine-plugins#107]
Fatal error: Uncaught Error: Call to undefined method aliuly\livesigns\FetchTask::isFinished() in phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressCSphp7/plugins/LiveSigns_v1.2.1php                                                                    7.phar/src/aliuly/livesigns/Main.php:138
Stack trace:
#0 phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressCSphp7/plugins/LiveSigns_v1.2.1php7.phar/src/aliuly/livesigns/Main.php(186): aliuly\livesigns\Main->scheduleRetrieve()
#1 phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressCSphp7/plugins/LiveSigns_v1.2.1php7.phar/src/aliuly/livesigns/common/PluginCallbackTask.php(49): aliuly\livesigns\Main->expireCac                                                                    he(7200, Object(aliuly\livesigns\common\PluginCallbackTask), 1964901)
#2 phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressCSphp7/ClearSky_1.1-php7.phar/src/pocketmine/scheduler/TaskHandler.php(130): aliuly\livesigns\common\PluginCallbackTask->onRun(19                                                                    64901)
#3 phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressCSphp7/ClearSky_1.1-php7.phar/ in phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressCSphp7/plugins/LiveSigns                                                                    _v1.2.1php7.phar/src/aliuly/livesigns/Main.php on line 138

**Comment by Aericio** [comment]
livesigns just got ripped.

**Comment by inxomnyaa** [comment]
This happens like.. 3 times a day.

**Comment by Aericio** [comment]
no, livesigns get real ripped. he deleted the whole plugin off this repo.

**Comment by alejandroliu** [comment]
I create a new repo for LiveSings at: https://github.com/Muirfield/LiveSigns
